name: runa
# concurrency:
#   group: runa
#   cancel-in-progress: true
on:
  workflow_dispatch:

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: hello
        shell: bash
        run: |
          echo "runa"
          echo "ref: ${{github.ref}}"



