name: runb
concurrency:
  group: runb
  cancel-in-progress: true
on:
  workflow_dispatch:

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        shell: bash
        run: |
          hello



