name: test
concurrency:
  group: test
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: create files
        shell: bash
        run: |
          mkdir -p ./test/a
          mkdir -p ./test/b
          echo "test1" > ./test/a/1
          echo "test2" > ./test/b/2

      - uses: tapclap/hook-workflow-action@main
        name: save
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflows: |
            - ruba.yaml
            - rubb.yaml


