name: test
concurrency:
  group: test
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  stage1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: create files
        shell: bash
        run: |
          echo "test" > ./1
          echo "test2" > ./2
          mkdir -p test/a
          echo "aaa" > test/a/1
          echo "bbb" > test/a/2

          ls -la 

      - uses: tapclap/s3-cache-action/save@main
        name: save
        with:
          secretKey: ${{ secrets.S3_CACHE_ACCESS_KEY }}
          accessKey: ${{ secrets.S3_CACHE_ACCESS_KEY_ID }}
          region: ${{ vars.S3_CACHE_REGION }}
          bucket: ${{ vars.S3_CACHE_BUCKET }}
          cache-list-keys: |
           dacdsv
                  dscdvvsd12120
                s
            - key: lalka/1
              path: ./1
            - key: lalka/2
              path: .\2
            - key: lalka/test1
              path: .\test1
            - key: lalka/test
              path: .\test

  stage2:
    runs-on: macos-latest
    needs: stage1
    steps:
      - uses: actions/checkout@main

      - uses: tapclap/s3-cache-action/restore@main
        name: restore
        with:
          secretKey: ${{ secrets.S3_CACHE_ACCESS_KEY }}
          accessKey: ${{ secrets.S3_CACHE_ACCESS_KEY_ID }}
          region: ${{ vars.S3_CACHE_REGION }}
          bucket: ${{ vars.S3_CACHE_BUCKET }}
          cache-list-keys: |
            - key: lalka/1
              path: ./1
            - key: lalka/3
              path: ./3
            - key: lalka/2
              path: ./2

      - name: check
        shell: bash
        run: |
          ls -la




