name: test
concurrency:
  group: test
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      # - name: Install GitHub CLI
      #   shell: bash
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gh

      - uses: tapclap/hook-workflow-action@main
        name: run workflows
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflows: |
            - runa.yaml
            - runb.yaml


