name: test
concurrency:
  group: test
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main


      # - name: create files
      #   shell: bash
      #   run: |
      #     echo "test" > ./1

      - uses: tapclap/s3-cache-action/restore@main
        name: restore
        with:
          secretKey: ${{ secrets.S3_CACHE_ACCESS_KEY }}
          accessKey: ${{ secrets.S3_CACHE_ACCESS_KEY_ID }}
          region: ${{ vars.S3_CACHE_REGION }}
          bucket: ${{ vars.S3_CACHE_BUCKET }}
          cache-list-keys: |
            - key: lalka/aaaa-bbbbb-ccccc-dsvdsvsdjfj2131232323dsvsvs-jsdvds/sfvsfafc123asdcac
              path: ./1
      
      - name: check
        run: |
          ls -la
          cat ./1


      # - uses: tapclap/s3-cache-action/save@main
      #   name: save
      #   with:
      #     secretKey: ${{ secrets.S3_CACHE_ACCESS_KEY }}
      #     accessKey: ${{ secrets.S3_CACHE_ACCESS_KEY_ID }}
      #     region: ${{ vars.S3_CACHE_REGION }}
      #     bucket: ${{ vars.S3_CACHE_BUCKET }}
      #     cache-list-keys: |
      #       - key: lalka/1
      #         path: ./1
      #       - key: lalka/2
      #         path: ./2
      #       - key: lalka/test1
      #         path: ./test1
      #       - key: lalka/test
      #         path: ./test


