name: test
concurrency:
  group: test
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: create files
        shell: bash
        run: |
          mkdir -p ./test/a
          mkdir -p ./test/b
          echo "test1" > ./test/a/1
          echo "test2" > ./test/b/2

      - uses: tapclap/s3-cache-action/test@test
        name: save
        with:
          secretKey: ''
          accessKey: ${{ secrets.S3_CACHE_ACCESS_KEY_ID }}
          region: ${{ vars.S3_CACHE_REGION }}
          bucket: ${{ vars.S3_CACHE_BUCKET }}
          cache-list-keys: |
            - key: lalka/uthycubyieuavmzehipnquisnhovdfmuibwwbkhhokacffjs
              path: ./test






