name: test
concurrency:
  group: test
  cancel-in-progress: true
on:
  workflow_dispatch:
    
  push:
    branches:
      - main
jobs:
  stage1:
    runs-on: [self-hosted, linux, docker]
    steps:
      - name: checkout
        uses: actions/checkout@main

      # - uses: tapclap/hook-workflow-action@main
      #   name: run workflows
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     workflows: |
      #       - runa.yaml
      #       - runb.yaml

      # - uses: tapclap/hook-workflow-action@main
      #   name: run workflows json 1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     workflows: |
      #       [
      #         "runa.yaml",
      #         "runb.yaml"
      #       ]

      # - uses: tapclap/hook-workflow-action@main
      #   name: run workflows json 2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     workflows: '["runa.yaml","runb.yaml"]'

